backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'blog'
    label: 'Blog'
    format: 'json'
    folder: 'assets/content/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'タイトル', name: 'title', widget: 'string' }
      - { label: '登校日', name: 'date', widget: 'datetime' }
      - {
          label: 'カテゴリ',
          name: 'category',
          widget: 'relation',
          collection: 'categories',
          searchFields: ['title', 'body'],
          valueField: 'title',
          displayFields: ['title'],
        }
      - { label: 'コンテンツ', name: 'content', widget: 'markdown' }

  - name: 'categories'
    label: 'カテゴリ'
    folder: 'categories'
    create: true
    fields:
      - { label: 'カテゴリ名', name: 'title', widget: 'string' }
      - { label: '説明文', name: 'body', widget: 'text' }
